services:
  rawat-inap-service:
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    container_name: rawat-inap-service
    image: adameds/rawat-inap:dev
    ports:
      - 8085:8085
    networks:
      - rawatinap-network
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
      SYNC_DB: ${SYNC_DB}
    restart: always
    volumes:
      - type: bind
        source: /home/admin/adameds/.env.vault
        target: /adameds-rawat-inap/.env.vault
networks:
  rawatinap-network:
    driver: bridge