services:
  rawat-inap-service:
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    container_name: api-adameds-rawatinap
    image: adameds/rawat-inap:dev
    ports:
      - 8085:8085
    networks:
      - rawatinap-network
    environment:
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
      SYNC_DB: ${SYNC_DB}
    restart: always
    # volumes:
    #   - type: bind
    #     source: /home/engineer/adameds/.env.vault
    #     target: /adameds-rawat-inap/.env.vault
networks:
  rawatinap-network:
    driver: bridge
